---
- name: Add line in sssd.conf and restart sssd service
  hosts: localhost
  become: yes
  tasks:

    - name: Ensure 'ignore_group_members = true' line exists after 'access_provider = ad'
      lineinfile:
        path: /etc/sssd/sssd.conf
        insertafter: '^access_provider = ad'
        line: 'ignore_group_members = true'
        state: present
        backup: yes  # Enables backup of the file before modification
      notify:
        - Restart SSSD

  handlers:
    - name: Restart SSSD
      service:
        name: sssd
        state: restarted
